# Generated by Django 5.2.14 on 2026-05-18 10:30

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(default='stripe', max_length=50)),
                ('provider_event_id', models.CharField(db_index=True, max_length=200, unique=True)),
                ('event_type', models.CharField(max_length=100)),
                ('payload', models.JSONField()),
                ('processed', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'payments_webhook_event',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentIntent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('provider', models.CharField(default='stripe', max_length=50)),
                ('provider_intent_id', models.CharField(db_index=True, max_length=200, unique=True)),
                ('status', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_intents', to='orders.order')),
            ],
            options={
                'db_table': 'payments_intent',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
