# Generated by Django 5.2.14 on 2026-05-18 10:30

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingZone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('countries', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=2), help_text='ISO 3166-1 alpha-2 codes', size=None)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'shipping_zone',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShippingMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('rate_type', models.CharField(choices=[('flat', 'Flat Rate'), ('weight', 'Weight-Based'), ('free', 'Free')], default='flat', max_length=10)),
                ('base_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('per_kg_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('min_days', models.PositiveSmallIntegerField(default=3)),
                ('max_days', models.PositiveSmallIntegerField(default=7)),
                ('is_active', models.BooleanField(default=True)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='methods', to='shipping.shippingzone')),
            ],
            options={
                'db_table': 'shipping_method',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
