# Generated by Django 5.2.14 on 2026-05-18 10:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('notification_type', models.CharField(choices=[('order_confirmation', 'Order Confirmation'), ('order_fulfilled', 'Order Fulfilled'), ('order_cancelled', 'Order Cancelled'), ('payment_failed', 'Payment Failed'), ('refund_issued', 'Refund Issued'), ('password_reset', 'Password Reset'), ('abandoned_cart', 'Abandoned Cart'), ('review_approved', 'Review Approved'), ('low_stock_alert', 'Low Stock Alert')], db_index=True, max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('object_id', models.UUIDField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['notification_type', 'created_at'], name='notificatio_notific_8fa9d0_idx'), models.Index(fields=['status', 'created_at'], name='notificatio_status_68c9bc_idx')],
            },
        ),
    ]
